services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  pgdata: